//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr14
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<int> IdSession { get; set; }
        public Nullable<int> IdSeat { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual Seats Seats { get; set; }
        public virtual Session Session { get; set; }
        public virtual Users Users { get; set; }
    }
}
